# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17lV91G0lWyI2zE9yFN-hs08MWpc6WGXA
"""

#Check if the given string is a palindrome or not irrespective of case

def palindrome(string): 
    string = string.lower().replace(' ', '') 
    fst, lst = 0, len(string) - 1 
    while(fst < lst): 
        if(string[fst] == string[lst]): 
            fst += 1 
            lst -= 1 
        else: 
            return "The string is not a palindrome." 
     
    return "The string is a palindrome." 
 str = input("Enter string : ") 
 print(palindrome(str1))

#The user enters a string and a substring. You have to print the number of times that the
#substring occurs in the given string. String traversal will take place from left to right, not from
#right to left 

def count_substring(string, sub_string):
    counter=0
    for i in range(len(string)-len(sub_string)):
        pos=string.find(sub_string)
        if pos!=-1:
            pos+=1
            string=string[pos+1:]
            counter+=1
    return count
if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    count = count_substring(string, sub_string)
    print(count)

# Create a basic rock paper scissors game.
# Take 2 user inputs from 2 players. You can use R, P and S are possible user inputs. Play the game
# for 10 rounds and declare the winner.
# Rules of the game
# Rock vs Scissors - Rock wins
# Rock vs Paper - Paper wins
# Paper vs Scissors - Scissor wins 


user_action = input("Enter a choice (rock, paper, scissors): ")
possible_actions = ["rock", "paper", "scissors"]
computer_action = random.choice(possible_actions)
print(f"\nYou chose {user_action}, computer chose {computer_action}.\n")

if user_action == computer_action:
    print(f"Both players selected {user_action}. It's a tie!")
elif user_action == "rock":
    if computer_action == "scissors":
        print("Rock smashes scissors! You win!")
    else:
        print("Paper covers rock! You lose.")
elif user_action == "paper":
    if computer_action == "rock":
        print("Paper covers rock! You win!")
    else:
        print("Scissors cuts paper! You lose.")
elif user_action == "scissors":
    if computer_action == "paper":
        print("Scissors cuts paper! You win!")
    else:
        print("Rock smashes scissors! You lose.")